all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    ca_host:
      hosts:
        localhost:
    deployment_targets:
      hosts:
        your_host:
          deployments:
            - src: certs/your_host/postgres.your_host/postgres.your_host.crt
              dest: /mnt/certs/
            - src: certs/your_host/postgres.your_host/postgres.your_host.key
              dest: /mnt/certs/
          notify:
            - sudo restart postgres
