all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    ca_host:
      hosts:
        localhost:
# uncomment for deploys
#    deployment_targets:
#      hosts:
#        your_host:
#          deployments:
#            - src: certs/your_host/postgres.your_host/postgres.your_host.crt
#              dest: /mnt/certs/
#            - src: certs/your_host/postgres.your_host/postgres.your_host.key
#              dest: /mnt/certs/
#          notify:
#            - sudo restart postgres
#        my-laptop:
#          deployments:
#            - src: certs/scytale_ca.crt
#              dest: /home/my_username/.postgresql
#              owner: "my_username"
#              group: "my_username"
#              symbolic_link: /home/my_username/.postgresql/root.crt
