- name: Set up Certificate Authority
  hosts: ca_host
  vars_files:
    - vars.yml
    - vars_vault.yml
  roles:
    - certificate_authority
    - service_certificates
    - client_certificates

- name: Deploy generate keys and certificates
  hosts: deployment_targets
  vars_files:
    - vars.yml
    - vars_vault.yml
  roles:
    - deployments
